# Generated by Django 4.2.2 on 2023-07-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('per_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rating_weight',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='target',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weight',
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=1000)),
                ('target', models.CharField(max_length=1000)),
                ('weight', models.CharField(blank=True, max_length=1000)),
                ('actual', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=1000)),
                ('rating_weight', models.CharField(blank=True, max_length=1000)),
                ('remark', models.CharField(max_length=1000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='per_review.employee')),
            ],
        ),
    ]
