# Generated by Django 4.2.2 on 2023-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_review', '0003_alter_employee_employee_results_alter_measure_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='rating_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
