# Generated by Django 4.2.2 on 2023-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_review', '0004_alter_measure_rating_weight_alter_measure_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='actual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='target',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
