# Generated by Django 4.2.2 on 2023-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_review', '0009_remove_employee_result_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='rating_weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
