# Generated by Django 4.2.2 on 2023-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_review', '0011_alter_measure_rating_alter_measure_rating_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='rating_weight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
